version: '3.1'

services:
    database:
        image: 'postgres:11'
        ports:
            - '8432:5432'
        environment:
            POSTGRES_DB: 'symfony'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data:
