<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Baseline: the schema as it was while libraries came from packagist.
 *
 * The production dataset predates this migration history, so there the baseline is marked as executed
 * instead of being run:
 *
 *     bin/console doctrine:migrations:sync-metadata-storage
 *     bin/console doctrine:migrations:version 'DoctrineMigrations\Version20260731011704' --add
 *
 * A fresh database runs it and is transformed by the next migration, ending up in the same shape.
 */
final class Version20260731011704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline of the packagist based schema (project, library, tag)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, vendor VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE5E237E06 ON project (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EEF52233F6 ON project (vendor)');

        $this->addSql('CREATE TABLE library (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, repository_url VARCHAR(255) NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A18098BC5E237E06 ON library (name)');
        $this->addSql('CREATE INDEX IDX_A18098BC166D1F9C ON library (project_id)');

        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lines_of_code INT NOT NULL, average_complexity DOUBLE PRECISION NOT NULL, library_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_389B783FE2541D7 ON tag (library_id)');
        $this->addSql('CREATE UNIQUE INDEX lib_tag ON tag (library_id, name)');

        $this->addSql('ALTER TABLE library ADD CONSTRAINT FK_A18098BC166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT FK_389B783FE2541D7 FOREIGN KEY (library_id) REFERENCES library (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tag DROP CONSTRAINT FK_389B783FE2541D7');
        $this->addSql('ALTER TABLE library DROP CONSTRAINT FK_A18098BC166D1F9C');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE library');
        $this->addSql('DROP TABLE project');
    }
}
