<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Hands the generation of ids over to PostgreSQL, where the ORM used to do it itself.
 *
 * On PostgreSQL, ORM 2 generated ids by reading a sequence before the insert, so the columns it created
 * are a plain `INT NOT NULL` next to a standalone `<table>_id_seq`. ORM 3 leaves the id out of the INSERT
 * and expects the database to fill it in, which those columns cannot: every write failed with a not-null
 * violation on `id`, from the submission form down to the tags an analysis writes.
 *
 * Only the tables that predate the baseline are affected - anything created from it is an identity column
 * already, which is why every table is checked instead of altered blindly.
 */
final class Version20260731110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Turn the id columns inherited from ORM 2 into identity columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            DO $$
            DECLARE
                target TEXT;
            BEGIN
                FOREACH target IN ARRAY ARRAY['project', 'repository', 'tag'] LOOP
                    -- anything but a column waiting to be converted is left alone, missing tables included
                    CONTINUE WHEN 'NO' IS DISTINCT FROM (
                        SELECT is_identity
                        FROM information_schema.columns
                        WHERE table_schema = CURRENT_SCHEMA()
                            AND table_name = target
                            AND column_name = 'id'
                    );

                    -- the sequence the ORM used to read is not attached to the column, so it goes away here
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP DEFAULT', target);
                    EXECUTE format('DROP SEQUENCE IF EXISTS %I', target || '_id_seq');
                    EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', target);

                    -- the identity starts counting at 1, the rows it has to coexist with do not
                    EXECUTE format(
                        'SELECT setval(pg_get_serial_sequence(%L, ''id''), COALESCE((SELECT MAX(id) FROM %I), 0) + 1, false)',
                        target,
                        target
                    );
                END LOOP;
            END $$;
            SQL);
    }

    public function down(Schema $schema): void
    {
        // Rolling back means handing id generation back to an ORM that no longer does it - there is no
        // version of this application left that could write to the result.
        $this->throwIrreversibleMigrationException('Identity columns are what every supported version of the ORM expects.');
    }
}
